#!/bin/sh
#
# Manage ALSA Master channel

colorAccent="#C3E88D"
grayAccent="#546E7A"

test "$1" = "-h" && echo "usage `basename $0` [+|-|!]" && exit 0

level() {
	VOL=$( amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]' )
	#OUT=$(SIZE=20 CHAR1="%{F${colorAccent}━%{F-}" CHAR2="%{F${colorAccent}─%{F-}" SEP="%{F${grayAccent}}━%{F-}" START='[' END=']' mkb $VOL)
	OUT=$(SIZE=20 CHAR1="━" CHAR2="─" SEP="━" START='' END='' mkb $VOL)

	echo "$OUT"
}

state() {
    amixer get Master | sed -n 's/^.*\[\(o[nf]\+\)]$/\1/p' | uniq
}

test $# -eq 0 && echo "`level` `state`" && exit 0

case $1 in
    +)      amixer set Master 5%+ >/dev/null;;
    -)      amixer set Master 5%- >/dev/null;;
    !)      amixer set Master toggle >/dev/null;;
    state|level) $1;;
    *)    amixer set Master $1 >/dev/null;;
esac
